#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_SETMUL")]
	public partial class DtClassSetmulDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_m_user(tbl_m_user instance);
    partial void Updatetbl_m_user(tbl_m_user instance);
    partial void Deletetbl_m_user(tbl_m_user instance);
    partial void Inserttbl_t_pembelian(tbl_t_pembelian instance);
    partial void Updatetbl_t_pembelian(tbl_t_pembelian instance);
    partial void Deletetbl_t_pembelian(tbl_t_pembelian instance);
    partial void Inserttbl_t_penjualan(tbl_t_penjualan instance);
    partial void Updatetbl_t_penjualan(tbl_t_penjualan instance);
    partial void Deletetbl_t_penjualan(tbl_t_penjualan instance);
    partial void Inserttbl_item_penjualan(tbl_item_penjualan instance);
    partial void Updatetbl_item_penjualan(tbl_item_penjualan instance);
    partial void Deletetbl_item_penjualan(tbl_item_penjualan instance);
    partial void Inserttbl_m_barang(tbl_m_barang instance);
    partial void Updatetbl_m_barang(tbl_m_barang instance);
    partial void Deletetbl_m_barang(tbl_m_barang instance);
    #endregion
		
		public DtClassSetmulDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_SETMULConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DtClassSetmulDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DtClassSetmulDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DtClassSetmulDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DtClassSetmulDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_m_user> tbl_m_users
		{
			get
			{
				return this.GetTable<tbl_m_user>();
			}
		}
		
		public System.Data.Linq.Table<tbl_t_pembelian> tbl_t_pembelians
		{
			get
			{
				return this.GetTable<tbl_t_pembelian>();
			}
		}
		
		public System.Data.Linq.Table<tbl_t_penjualan> tbl_t_penjualans
		{
			get
			{
				return this.GetTable<tbl_t_penjualan>();
			}
		}
		
		public System.Data.Linq.Table<tbl_item_penjualan> tbl_item_penjualans
		{
			get
			{
				return this.GetTable<tbl_item_penjualan>();
			}
		}
		
		public System.Data.Linq.Table<vw_report> vw_reports
		{
			get
			{
				return this.GetTable<vw_report>();
			}
		}
		
		public System.Data.Linq.Table<tbl_m_barang> tbl_m_barangs
		{
			get
			{
				return this.GetTable<tbl_m_barang>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cufn_GenerateNoTrans", IsComposable=true)]
		public string cufn_GenerateNoTrans()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cusp_chartbar_dashboard")]
		public ISingleResult<cusp_chartbar_dashboardResult> cusp_chartbar_dashboard([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tipe)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tipe);
			return ((ISingleResult<cusp_chartbar_dashboardResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cusp_count_dashboard")]
		public ISingleResult<cusp_count_dashboardResult> cusp_count_dashboard()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cusp_count_dashboardResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_m_user")]
	public partial class tbl_m_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _username;
		
		private string _nama_user;
		
		private string _password;
		
		private string _created_by;
		
		private System.Nullable<System.DateTime> _created_date;
		
		private string _modified_by;
		
		private System.Nullable<System.DateTime> _modified_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void Onnama_userChanging(string value);
    partial void Onnama_userChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Oncreated_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_dateChanged();
    partial void Onmodified_byChanging(string value);
    partial void Onmodified_byChanged();
    partial void Onmodified_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onmodified_dateChanged();
    #endregion
		
		public tbl_m_user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_user", DbType="VarChar(250)")]
		public string nama_user
		{
			get
			{
				return this._nama_user;
			}
			set
			{
				if ((this._nama_user != value))
				{
					this.Onnama_userChanging(value);
					this.SendPropertyChanging();
					this._nama_user = value;
					this.SendPropertyChanged("nama_user");
					this.Onnama_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(16)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="VarChar(50)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this.Oncreated_dateChanging(value);
					this.SendPropertyChanging();
					this._created_date = value;
					this.SendPropertyChanged("created_date");
					this.Oncreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="VarChar(50)")]
		public string modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this.Onmodified_byChanging(value);
					this.SendPropertyChanging();
					this._modified_by = value;
					this.SendPropertyChanged("modified_by");
					this.Onmodified_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> modified_date
		{
			get
			{
				return this._modified_date;
			}
			set
			{
				if ((this._modified_date != value))
				{
					this.Onmodified_dateChanging(value);
					this.SendPropertyChanging();
					this._modified_date = value;
					this.SendPropertyChanged("modified_date");
					this.Onmodified_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_t_pembelian")]
	public partial class tbl_t_pembelian : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _pid;
		
		private System.Nullable<System.DateTime> _tanggal_transaksi;
		
		private string _kode_barang;
		
		private string _nama_barang;
		
		private string _pengukuran;
		
		private System.Nullable<int> _jumlah_pembelian;
		
		private System.Nullable<decimal> _harga;
		
		private System.Nullable<decimal> _total;
		
		private string _created_by;
		
		private System.Nullable<System.DateTime> _created_date;
		
		private string _modified_by;
		
		private System.Nullable<System.DateTime> _modified_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpidChanging(string value);
    partial void OnpidChanged();
    partial void Ontanggal_transaksiChanging(System.Nullable<System.DateTime> value);
    partial void Ontanggal_transaksiChanged();
    partial void Onkode_barangChanging(string value);
    partial void Onkode_barangChanged();
    partial void Onnama_barangChanging(string value);
    partial void Onnama_barangChanged();
    partial void OnpengukuranChanging(string value);
    partial void OnpengukuranChanged();
    partial void Onjumlah_pembelianChanging(System.Nullable<int> value);
    partial void Onjumlah_pembelianChanged();
    partial void OnhargaChanging(System.Nullable<decimal> value);
    partial void OnhargaChanged();
    partial void OntotalChanging(System.Nullable<decimal> value);
    partial void OntotalChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Oncreated_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_dateChanged();
    partial void Onmodified_byChanging(string value);
    partial void Onmodified_byChanged();
    partial void Onmodified_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onmodified_dateChanged();
    #endregion
		
		public tbl_t_pembelian()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string pid
		{
			get
			{
				return this._pid;
			}
			set
			{
				if ((this._pid != value))
				{
					this.OnpidChanging(value);
					this.SendPropertyChanging();
					this._pid = value;
					this.SendPropertyChanged("pid");
					this.OnpidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal_transaksi", DbType="Date")]
		public System.Nullable<System.DateTime> tanggal_transaksi
		{
			get
			{
				return this._tanggal_transaksi;
			}
			set
			{
				if ((this._tanggal_transaksi != value))
				{
					this.Ontanggal_transaksiChanging(value);
					this.SendPropertyChanging();
					this._tanggal_transaksi = value;
					this.SendPropertyChanged("tanggal_transaksi");
					this.Ontanggal_transaksiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_barang", DbType="VarChar(50)")]
		public string kode_barang
		{
			get
			{
				return this._kode_barang;
			}
			set
			{
				if ((this._kode_barang != value))
				{
					this.Onkode_barangChanging(value);
					this.SendPropertyChanging();
					this._kode_barang = value;
					this.SendPropertyChanged("kode_barang");
					this.Onkode_barangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_barang", DbType="VarChar(50)")]
		public string nama_barang
		{
			get
			{
				return this._nama_barang;
			}
			set
			{
				if ((this._nama_barang != value))
				{
					this.Onnama_barangChanging(value);
					this.SendPropertyChanging();
					this._nama_barang = value;
					this.SendPropertyChanged("nama_barang");
					this.Onnama_barangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pengukuran", DbType="VarChar(50)")]
		public string pengukuran
		{
			get
			{
				return this._pengukuran;
			}
			set
			{
				if ((this._pengukuran != value))
				{
					this.OnpengukuranChanging(value);
					this.SendPropertyChanging();
					this._pengukuran = value;
					this.SendPropertyChanged("pengukuran");
					this.OnpengukuranChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jumlah_pembelian", DbType="Int")]
		public System.Nullable<int> jumlah_pembelian
		{
			get
			{
				return this._jumlah_pembelian;
			}
			set
			{
				if ((this._jumlah_pembelian != value))
				{
					this.Onjumlah_pembelianChanging(value);
					this.SendPropertyChanging();
					this._jumlah_pembelian = value;
					this.SendPropertyChanged("jumlah_pembelian");
					this.Onjumlah_pembelianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_harga", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> harga
		{
			get
			{
				return this._harga;
			}
			set
			{
				if ((this._harga != value))
				{
					this.OnhargaChanging(value);
					this.SendPropertyChanging();
					this._harga = value;
					this.SendPropertyChanged("harga");
					this.OnhargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="VarChar(50)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this.Oncreated_dateChanging(value);
					this.SendPropertyChanging();
					this._created_date = value;
					this.SendPropertyChanged("created_date");
					this.Oncreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="VarChar(50)")]
		public string modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this.Onmodified_byChanging(value);
					this.SendPropertyChanging();
					this._modified_by = value;
					this.SendPropertyChanged("modified_by");
					this.Onmodified_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> modified_date
		{
			get
			{
				return this._modified_date;
			}
			set
			{
				if ((this._modified_date != value))
				{
					this.Onmodified_dateChanging(value);
					this.SendPropertyChanging();
					this._modified_date = value;
					this.SendPropertyChanged("modified_date");
					this.Onmodified_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_t_penjualan")]
	public partial class tbl_t_penjualan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _no_transaksi;
		
		private System.Nullable<System.DateTime> _tanggal_transaksi;
		
		private System.Nullable<decimal> _total;
		
		private string _created_by;
		
		private System.Nullable<System.DateTime> _created_date;
		
		private string _modified_by;
		
		private System.Nullable<System.DateTime> _modified_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onno_transaksiChanging(string value);
    partial void Onno_transaksiChanged();
    partial void Ontanggal_transaksiChanging(System.Nullable<System.DateTime> value);
    partial void Ontanggal_transaksiChanged();
    partial void OntotalChanging(System.Nullable<decimal> value);
    partial void OntotalChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Oncreated_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_dateChanged();
    partial void Onmodified_byChanging(string value);
    partial void Onmodified_byChanged();
    partial void Onmodified_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onmodified_dateChanged();
    #endregion
		
		public tbl_t_penjualan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_transaksi", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string no_transaksi
		{
			get
			{
				return this._no_transaksi;
			}
			set
			{
				if ((this._no_transaksi != value))
				{
					this.Onno_transaksiChanging(value);
					this.SendPropertyChanging();
					this._no_transaksi = value;
					this.SendPropertyChanged("no_transaksi");
					this.Onno_transaksiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal_transaksi", DbType="Date")]
		public System.Nullable<System.DateTime> tanggal_transaksi
		{
			get
			{
				return this._tanggal_transaksi;
			}
			set
			{
				if ((this._tanggal_transaksi != value))
				{
					this.Ontanggal_transaksiChanging(value);
					this.SendPropertyChanging();
					this._tanggal_transaksi = value;
					this.SendPropertyChanged("tanggal_transaksi");
					this.Ontanggal_transaksiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="VarChar(50)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this.Oncreated_dateChanging(value);
					this.SendPropertyChanging();
					this._created_date = value;
					this.SendPropertyChanged("created_date");
					this.Oncreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="VarChar(50)")]
		public string modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this.Onmodified_byChanging(value);
					this.SendPropertyChanging();
					this._modified_by = value;
					this.SendPropertyChanged("modified_by");
					this.Onmodified_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> modified_date
		{
			get
			{
				return this._modified_date;
			}
			set
			{
				if ((this._modified_date != value))
				{
					this.Onmodified_dateChanging(value);
					this.SendPropertyChanging();
					this._modified_date = value;
					this.SendPropertyChanged("modified_date");
					this.Onmodified_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_item_penjualan")]
	public partial class tbl_item_penjualan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _pid;
		
		private string _no_transaksi;
		
		private string _kode_barang;
		
		private string _nama_barang;
		
		private System.Nullable<int> _jumlah;
		
		private System.Nullable<decimal> _harga_satuan;
		
		private System.Nullable<decimal> _harga_total;
		
		private string _created_by;
		
		private System.Nullable<System.DateTime> _created_date;
		
		private string _modified_by;
		
		private System.Nullable<System.DateTime> _modified_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpidChanging(string value);
    partial void OnpidChanged();
    partial void Onno_transaksiChanging(string value);
    partial void Onno_transaksiChanged();
    partial void Onkode_barangChanging(string value);
    partial void Onkode_barangChanged();
    partial void Onnama_barangChanging(string value);
    partial void Onnama_barangChanged();
    partial void OnjumlahChanging(System.Nullable<int> value);
    partial void OnjumlahChanged();
    partial void Onharga_satuanChanging(System.Nullable<decimal> value);
    partial void Onharga_satuanChanged();
    partial void Onharga_totalChanging(System.Nullable<decimal> value);
    partial void Onharga_totalChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Oncreated_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_dateChanged();
    partial void Onmodified_byChanging(string value);
    partial void Onmodified_byChanged();
    partial void Onmodified_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onmodified_dateChanged();
    #endregion
		
		public tbl_item_penjualan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string pid
		{
			get
			{
				return this._pid;
			}
			set
			{
				if ((this._pid != value))
				{
					this.OnpidChanging(value);
					this.SendPropertyChanging();
					this._pid = value;
					this.SendPropertyChanged("pid");
					this.OnpidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_transaksi", DbType="VarChar(50)")]
		public string no_transaksi
		{
			get
			{
				return this._no_transaksi;
			}
			set
			{
				if ((this._no_transaksi != value))
				{
					this.Onno_transaksiChanging(value);
					this.SendPropertyChanging();
					this._no_transaksi = value;
					this.SendPropertyChanged("no_transaksi");
					this.Onno_transaksiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_barang", DbType="VarChar(50)")]
		public string kode_barang
		{
			get
			{
				return this._kode_barang;
			}
			set
			{
				if ((this._kode_barang != value))
				{
					this.Onkode_barangChanging(value);
					this.SendPropertyChanging();
					this._kode_barang = value;
					this.SendPropertyChanged("kode_barang");
					this.Onkode_barangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_barang", DbType="VarChar(50)")]
		public string nama_barang
		{
			get
			{
				return this._nama_barang;
			}
			set
			{
				if ((this._nama_barang != value))
				{
					this.Onnama_barangChanging(value);
					this.SendPropertyChanging();
					this._nama_barang = value;
					this.SendPropertyChanged("nama_barang");
					this.Onnama_barangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jumlah", DbType="Int")]
		public System.Nullable<int> jumlah
		{
			get
			{
				return this._jumlah;
			}
			set
			{
				if ((this._jumlah != value))
				{
					this.OnjumlahChanging(value);
					this.SendPropertyChanging();
					this._jumlah = value;
					this.SendPropertyChanged("jumlah");
					this.OnjumlahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_harga_satuan", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> harga_satuan
		{
			get
			{
				return this._harga_satuan;
			}
			set
			{
				if ((this._harga_satuan != value))
				{
					this.Onharga_satuanChanging(value);
					this.SendPropertyChanging();
					this._harga_satuan = value;
					this.SendPropertyChanged("harga_satuan");
					this.Onharga_satuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_harga_total", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> harga_total
		{
			get
			{
				return this._harga_total;
			}
			set
			{
				if ((this._harga_total != value))
				{
					this.Onharga_totalChanging(value);
					this.SendPropertyChanging();
					this._harga_total = value;
					this.SendPropertyChanged("harga_total");
					this.Onharga_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="VarChar(50)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this.Oncreated_dateChanging(value);
					this.SendPropertyChanging();
					this._created_date = value;
					this.SendPropertyChanged("created_date");
					this.Oncreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="VarChar(50)")]
		public string modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this.Onmodified_byChanging(value);
					this.SendPropertyChanging();
					this._modified_by = value;
					this.SendPropertyChanged("modified_by");
					this.Onmodified_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> modified_date
		{
			get
			{
				return this._modified_date;
			}
			set
			{
				if ((this._modified_date != value))
				{
					this.Onmodified_dateChanging(value);
					this.SendPropertyChanging();
					this._modified_date = value;
					this.SendPropertyChanged("modified_date");
					this.Onmodified_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_report")]
	public partial class vw_report
	{
		
		private string _periode;
		
		private decimal _pemasukan;
		
		private decimal _pembelian;
		
		public vw_report()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_periode", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string periode
		{
			get
			{
				return this._periode;
			}
			set
			{
				if ((this._periode != value))
				{
					this._periode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pemasukan", DbType="Decimal(38,0) NOT NULL")]
		public decimal pemasukan
		{
			get
			{
				return this._pemasukan;
			}
			set
			{
				if ((this._pemasukan != value))
				{
					this._pemasukan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pembelian", DbType="Decimal(38,0) NOT NULL")]
		public decimal pembelian
		{
			get
			{
				return this._pembelian;
			}
			set
			{
				if ((this._pembelian != value))
				{
					this._pembelian = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_m_barang")]
	public partial class tbl_m_barang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _kode_barang;
		
		private string _nama_barang;
		
		private string _pengukuran;
		
		private string _stok_barang;
		
		private string _harga_barang;
		
		private string _jumlah_berat;
		
		private string _tgl_msk_gudang;
		
		private string _tgl_exp;
		
		private string _created_by;
		
		private System.Nullable<System.DateTime> _created_date;
		
		private string _modified_by;
		
		private System.Nullable<System.DateTime> _modified_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkode_barangChanging(string value);
    partial void Onkode_barangChanged();
    partial void Onnama_barangChanging(string value);
    partial void Onnama_barangChanged();
    partial void OnpengukuranChanging(string value);
    partial void OnpengukuranChanged();
    partial void Onstok_barangChanging(string value);
    partial void Onstok_barangChanged();
    partial void Onharga_barangChanging(string value);
    partial void Onharga_barangChanged();
    partial void Onjumlah_beratChanging(string value);
    partial void Onjumlah_beratChanged();
    partial void Ontgl_msk_gudangChanging(string value);
    partial void Ontgl_msk_gudangChanged();
    partial void Ontgl_expChanging(string value);
    partial void Ontgl_expChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Oncreated_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_dateChanged();
    partial void Onmodified_byChanging(string value);
    partial void Onmodified_byChanged();
    partial void Onmodified_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onmodified_dateChanged();
    #endregion
		
		public tbl_m_barang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_barang", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string kode_barang
		{
			get
			{
				return this._kode_barang;
			}
			set
			{
				if ((this._kode_barang != value))
				{
					this.Onkode_barangChanging(value);
					this.SendPropertyChanging();
					this._kode_barang = value;
					this.SendPropertyChanged("kode_barang");
					this.Onkode_barangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_barang", DbType="VarChar(50)")]
		public string nama_barang
		{
			get
			{
				return this._nama_barang;
			}
			set
			{
				if ((this._nama_barang != value))
				{
					this.Onnama_barangChanging(value);
					this.SendPropertyChanging();
					this._nama_barang = value;
					this.SendPropertyChanged("nama_barang");
					this.Onnama_barangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pengukuran", DbType="VarChar(20)")]
		public string pengukuran
		{
			get
			{
				return this._pengukuran;
			}
			set
			{
				if ((this._pengukuran != value))
				{
					this.OnpengukuranChanging(value);
					this.SendPropertyChanging();
					this._pengukuran = value;
					this.SendPropertyChanged("pengukuran");
					this.OnpengukuranChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stok_barang", DbType="VarChar(10)")]
		public string stok_barang
		{
			get
			{
				return this._stok_barang;
			}
			set
			{
				if ((this._stok_barang != value))
				{
					this.Onstok_barangChanging(value);
					this.SendPropertyChanging();
					this._stok_barang = value;
					this.SendPropertyChanged("stok_barang");
					this.Onstok_barangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_harga_barang", DbType="VarChar(20)")]
		public string harga_barang
		{
			get
			{
				return this._harga_barang;
			}
			set
			{
				if ((this._harga_barang != value))
				{
					this.Onharga_barangChanging(value);
					this.SendPropertyChanging();
					this._harga_barang = value;
					this.SendPropertyChanged("harga_barang");
					this.Onharga_barangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jumlah_berat", DbType="VarChar(15)")]
		public string jumlah_berat
		{
			get
			{
				return this._jumlah_berat;
			}
			set
			{
				if ((this._jumlah_berat != value))
				{
					this.Onjumlah_beratChanging(value);
					this.SendPropertyChanging();
					this._jumlah_berat = value;
					this.SendPropertyChanged("jumlah_berat");
					this.Onjumlah_beratChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_msk_gudang", DbType="VarChar(15)")]
		public string tgl_msk_gudang
		{
			get
			{
				return this._tgl_msk_gudang;
			}
			set
			{
				if ((this._tgl_msk_gudang != value))
				{
					this.Ontgl_msk_gudangChanging(value);
					this.SendPropertyChanging();
					this._tgl_msk_gudang = value;
					this.SendPropertyChanged("tgl_msk_gudang");
					this.Ontgl_msk_gudangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_exp", DbType="VarChar(15)")]
		public string tgl_exp
		{
			get
			{
				return this._tgl_exp;
			}
			set
			{
				if ((this._tgl_exp != value))
				{
					this.Ontgl_expChanging(value);
					this.SendPropertyChanging();
					this._tgl_exp = value;
					this.SendPropertyChanged("tgl_exp");
					this.Ontgl_expChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="VarChar(50)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this.Oncreated_dateChanging(value);
					this.SendPropertyChanging();
					this._created_date = value;
					this.SendPropertyChanged("created_date");
					this.Oncreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="VarChar(50)")]
		public string modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this.Onmodified_byChanging(value);
					this.SendPropertyChanging();
					this._modified_by = value;
					this.SendPropertyChanged("modified_by");
					this.Onmodified_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> modified_date
		{
			get
			{
				return this._modified_date;
			}
			set
			{
				if ((this._modified_date != value))
				{
					this.Onmodified_dateChanging(value);
					this.SendPropertyChanging();
					this._modified_date = value;
					this.SendPropertyChanged("modified_date");
					this.Onmodified_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class cusp_chartbar_dashboardResult
	{
		
		private System.Nullable<decimal> _total;
		
		private string _jenis;
		
		public cusp_chartbar_dashboardResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jenis", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string jenis
		{
			get
			{
				return this._jenis;
			}
			set
			{
				if ((this._jenis != value))
				{
					this._jenis = value;
				}
			}
		}
	}
	
	public partial class cusp_count_dashboardResult
	{
		
		private System.Nullable<decimal> _penjualan_hari_ini;
		
		private System.Nullable<decimal> _penjualan_bulan_ini;
		
		private System.Nullable<decimal> _penjualan_tahun_ini;
		
		private System.Nullable<decimal> _penjualan_tahun_lalu;
		
		public cusp_count_dashboardResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_penjualan_hari_ini", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> penjualan_hari_ini
		{
			get
			{
				return this._penjualan_hari_ini;
			}
			set
			{
				if ((this._penjualan_hari_ini != value))
				{
					this._penjualan_hari_ini = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_penjualan_bulan_ini", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> penjualan_bulan_ini
		{
			get
			{
				return this._penjualan_bulan_ini;
			}
			set
			{
				if ((this._penjualan_bulan_ini != value))
				{
					this._penjualan_bulan_ini = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_penjualan_tahun_ini", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> penjualan_tahun_ini
		{
			get
			{
				return this._penjualan_tahun_ini;
			}
			set
			{
				if ((this._penjualan_tahun_ini != value))
				{
					this._penjualan_tahun_ini = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_penjualan_tahun_lalu", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> penjualan_tahun_lalu
		{
			get
			{
				return this._penjualan_tahun_lalu;
			}
			set
			{
				if ((this._penjualan_tahun_lalu != value))
				{
					this._penjualan_tahun_lalu = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
